// Auto-generated by sync-projects.js — do not edit manually.
// Add or edit .md files in the content/ folder, then run:  node sync-projects.js

const projects = [
    {
        "id": "phygital-cocreation",
        "title": "Phygital co-creation",
        "category": "publications",
        "description": "",
        "tags": [
            "co-creation",
            "publication",
            "hybrid planner",
            "ai",
            "phygital"
        ],
        "video": "https://pub-6f1f448701a747e7a713d859704dce6c.r2.dev/PhygitalCocreation_viktoriaSandor.mov",
        "image": "",
        "embed": "",
        "videoStart": "",
        "detailPage": "https://doi.org/10.14627/537754004",
        "year": "2025",
        "type": "co-creation tool, journal publication",
        "institution": "JODLA Digital Landscape Architecture",
        "links": []
    },
    {
        "id": "vitality-city",
        "title": "Vitality City",
        "category": "research",
        "description": "",
        "tags": [
            "energy",
            "dashboard",
            "tool",
            "data",
            "interoperation",
            "simulation"
        ],
        "video": "",
        "image": "videos\\vitality.gif",
        "embed": "",
        "videoStart": "",
        "detailPage": "https://klimaneutralestadt.at/de/projekte/tiks/vitality-city.php",
        "year": "2024–2027",
        "type": "AIT research project",
        "institution": "FFG, AIT",
        "links": []
    },
    {
        "id": "architecture-visualization",
        "title": "Architecture Visualization",
        "category": "teaching",
        "description": "",
        "tags": [
            "storytelling"
        ],
        "video": "",
        "image": "images\\Visualization.jpg",
        "embed": "",
        "videoStart": "",
        "detailPage": "https://sites.google.com/view/vis-stor/lectures",
        "year": "2024",
        "type": "seminar (BA)",
        "institution": "integratives design – University Innsbruck",
        "links": []
    },
    {
        "id": "energy-design",
        "title": "Energy Design",
        "category": "teaching",
        "description": "",
        "tags": [
            "energy",
            "teaching"
        ],
        "video": "",
        "image": "images\\energydesign.jpg",
        "embed": "",
        "videoStart": "",
        "detailPage": "https://sites.google.com/view/energydesign24ss/classes",
        "year": "2024",
        "type": "seminar (BA)",
        "institution": "EKA – University Tallinn",
        "links": []
    },
    {
        "id": "lca-miro",
        "title": "LCA Miro",
        "category": "presentations",
        "description": "",
        "tags": [
            "hackathon",
            "circularity",
            "co-creation",
            "presentation",
            "tool",
            "ai"
        ],
        "video": "https://pub-6f1f448701a747e7a713d859704dce6c.r2.dev/lca%20miro.MOV",
        "image": "",
        "embed": "",
        "videoStart": "",
        "detailPage": "https://www.youtube.com/watch?v=eSaVuwWMKCw",
        "year": "2024",
        "type": "hackathon – best mashup project",
        "institution": "AEC Zürich Hackathon",
        "links": []
    },
    {
        "id": "plate-to-planet",
        "title": "Plate to Planet",
        "category": "teaching",
        "description": "",
        "tags": [
            "food",
            "circularity"
        ],
        "video": "",
        "image": "images\\p2p.jpg",
        "embed": "",
        "videoStart": "",
        "detailPage": "https://sites.google.com/view/platetoplanet/about-the-course",
        "year": "2024",
        "type": "design studio (BA)",
        "institution": "University Innsbruck | Integratives Design",
        "links": []
    },
    {
        "id": "street-swap",
        "title": "Street Swap",
        "category": "teaching",
        "description": "",
        "tags": [
            "public space",
            "pedestrianization",
            "hybrid",
            "tool",
            "co-creation",
            "workshop",
            "ai"
        ],
        "video": "https://pub-6f1f448701a747e7a713d859704dce6c.r2.dev/streetswap.mp4",
        "image": "",
        "embed": "",
        "videoStart": "",
        "detailPage": "https://sites.google.com/view/streetswap/home",
        "year": "2024",
        "type": "workshop",
        "institution": "Vienna Architecture Summerschool",
        "links": []
    },
    {
        "id": "the-permanently-temporary-seminar",
        "title": "The Permanently Temporary",
        "category": "teaching",
        "description": "",
        "tags": [
            "storytelling",
            "time"
        ],
        "video": "https://youtu.be/lKR4WPFetuU?si=rAPehZUhc3FfftZM",
        "image": "",
        "embed": "",
        "videoStart": "00:04",
        "detailPage": "https://sites.google.com/view/storyseminar01/",
        "year": "2024",
        "type": "seminar (MA)",
        "institution": "",
        "links": []
    },
    {
        "id": "collaborative-urban-planning-speckle",
        "title": "Collaborative Urban Planning Demo",
        "category": "presentations",
        "description": "",
        "tags": [
            "computational design",
            "urban planning",
            "hackathon",
            "co-creation",
            "hybrid",
            "tool",
            "ai"
        ],
        "video": "https://youtu.be/LyMGmdtcZlI?si=mZU6CVmh7ShlC9kF",
        "image": "",
        "embed": "",
        "videoStart": "00:14",
        "detailPage": "https://www.youtube.com/playlist?list=PLlI5Dyt2HaEstV9bPCNPMn1q_S1_GDkeB",
        "year": "2023",
        "type": "speckle hackathon",
        "institution": "Speckle Con, AIT",
        "links": []
    },
    {
        "id": "computational-urban-planning-codec-hackathon",
        "title": "Computational Urban Planning Demo",
        "category": "presentations",
        "description": "",
        "tags": [
            "computational design",
            "ar",
            "demo",
            "urban planning",
            "hackathon",
            "ai",
            "interoperation",
            "speckle",
            "co-creation",
            "tool",
            "hybrid",
            "dashboard"
        ],
        "video": "https://youtu.be/Y2T1LDh5E44?si=r6uIzvhohLlsHG4N",
        "image": "",
        "embed": "",
        "videoStart": "",
        "detailPage": "https://www.ait.ac.at/fileadmin/cmc/06_Media/Presseaussendungen/2023/20230330_Pressaussendung_AIT_Codec_Symposium_final_en.pdf",
        "year": "2023",
        "type": "codec hackathon",
        "institution": "CODEC symposium",
        "links": []
    },
    {
        "id": "hybrid-planner",
        "title": "Hybrid Planner",
        "category": "project, research",
        "description": "",
        "tags": [
            "co-creation",
            "hybrid",
            "ai",
            "phygital",
            "computational design",
            "dashboard"
        ],
        "video": "https://www.youtube.com/watch?v=hZDA1gidvXs",
        "image": "",
        "embed": "",
        "videoStart": "00:40",
        "detailPage": "https://doi.org/10.14627/537754004",
        "year": "2023",
        "type": "co-creation tool, ar, demo",
        "institution": "AIT Digital Resilient Cities",
        "links": []
    },
    {
        "id": "pocytif",
        "title": "Pocytif",
        "category": "research",
        "description": "",
        "tags": [
            "urban resilience",
            "nature-based solutions",
            "energy"
        ],
        "video": "https://youtu.be/kcCFqeYbmOw?si=9gExNUNkncg6eRjp",
        "image": "",
        "embed": "",
        "videoStart": "",
        "detailPage": "https://pocityf.eu/",
        "year": "2023",
        "type": "AIT research project",
        "institution": "Speckle Con",
        "links": []
    },
    {
        "id": "point-pixel-print",
        "title": "Point Pixel Print",
        "category": "teaching",
        "description": "",
        "tags": [
            "point cloud notation",
            "clay printing",
            "karamba"
        ],
        "video": "",
        "image": "images\\point-pixel-print.jfif",
        "embed": "",
        "videoStart": "",
        "detailPage": "",
        "year": "2023",
        "type": "methods of materialization (BA)",
        "institution": "isd – University Innsbruck",
        "links": []
    },
    {
        "id": "collapsing-complexities",
        "title": "Collapsing Complexities",
        "category": "publications",
        "description": "",
        "tags": [
            "encoding",
            "point cloud notation",
            "ai",
            "gan",
            "publication",
            "volumetric design"
        ],
        "video": "",
        "image": "images\\Collapsing-complexities.jpg",
        "embed": "",
        "videoStart": "",
        "detailPage": "https://doi.org/10.1007/978-981-19-8637-6_32",
        "year": "2022",
        "type": "conference proceeding",
        "institution": "DIGITAL FUTURES University Innsbruck|ISD",
        "links": []
    },
    {
        "id": "guilderland",
        "title": "Guilderland",
        "category": "teaching",
        "description": "",
        "tags": [
            "co-creation"
        ],
        "video": "",
        "image": "images\\guilderland.jfif",
        "embed": "",
        "videoStart": "",
        "detailPage": "https://sites.google.com/view/guilderland/",
        "year": "2022",
        "type": "design studio (BA)",
        "institution": "University Innsbruck | isd",
        "links": []
    },
    {
        "id": "clouder-publication",
        "title": "Hybrid Immediacy",
        "category": "research, publication",
        "description": "",
        "tags": [
            "publication",
            "hybrid",
            "tool",
            "phygital",
            "point cloud notation",
            "ai",
            "volumetric design"
        ],
        "video": "",
        "image": "images\\Hybrid Immediacy.jpg",
        "embed": "",
        "videoStart": "",
        "detailPage": "https://doi.org/10.1007/978-3-031-13249-0_48",
        "year": "2022",
        "type": "publication",
        "institution": "University Innsbruck | ISD, DMSB",
        "links": []
    },
    {
        "id": "leaning-spatiality",
        "title": "Learning Spatiality",
        "category": "publications",
        "description": "",
        "tags": [
            "encoding",
            "point cloud notation",
            "ai",
            "gan",
            "publication",
            "volumetric design",
            "section"
        ],
        "video": "",
        "image": "images\\learning-spatiality.gif",
        "embed": "",
        "videoStart": "",
        "detailPage": "https://www.researchgate.net/publication/364230748_Learning_Spatiality_-_A_GAN_method_for_designing_architectural_models_through_labelled_sections",
        "year": "2022",
        "type": "conference proceeding",
        "institution": "ECAADE, University Innsbruck|ISD",
        "links": []
    },
    {
        "id": "naschpark",
        "title": "Naschpark",
        "category": "teaching",
        "description": "",
        "tags": [
            "co-creation",
            "vienna",
            "public space"
        ],
        "video": "videos\\naschpark.MOV",
        "image": "",
        "embed": "",
        "videoStart": "",
        "detailPage": "https://sites.google.com/view/naschpark/naschpark?authuser=0",
        "year": "2022",
        "type": "design studio (BA)",
        "institution": "isd – University Innsbruck",
        "links": []
    },
    {
        "id": "pixel-plots",
        "title": "Pixel Plots",
        "category": "teaching",
        "description": "",
        "tags": [
            "ai",
            "gan",
            "point cloud notation",
            "encoding"
        ],
        "video": "https://pub-6f1f448701a747e7a713d859704dce6c.r2.dev/collapsing%20complexities_.mp4",
        "image": "",
        "embed": "",
        "videoStart": "",
        "detailPage": "https://doi.org/10.1007/978-981-19-8637-6_32",
        "year": "2022",
        "type": "methods of materialization (BA)",
        "institution": "isd – University Innsbruck",
        "links": []
    },
    {
        "id": "point-to-print",
        "title": "Point to Print",
        "category": "teaching",
        "description": "",
        "tags": [
            "point printing",
            "clay printing",
            "point cloud notation",
            "encoding",
            "ai"
        ],
        "video": "videos\\Point-to-Print-Stuttgart.mp4",
        "image": "",
        "embed": "",
        "videoStart": "00:10",
        "detailPage": "https://docs.google.com/presentation/d/e/2PACX-1vRrSfyyyWOfSe2GN_cBO1mZDRJHFBpjXIFQogJPrZ-XCKCmE7GOPiubxxK0_DaCbJOkUS9OxoMNvhAp/pub?start=true&loop=false&delayms=3000",
        "year": "2022",
        "type": "workshop",
        "institution": "AEC Autumn School Stuttgart",
        "links": []
    },
    {
        "id": "porthouse",
        "title": "Porthouse",
        "category": "teaching",
        "description": "",
        "tags": [
            "revitalization",
            "dataviz"
        ],
        "video": "",
        "image": "",
        "embed": "",
        "videoStart": "",
        "detailPage": "projects/porthouse.html",
        "year": "2022",
        "type": "design studio (BA thesis)",
        "institution": "isd – University Innsbruck",
        "links": []
    },
    {
        "id": "clouder",
        "title": "Clouder",
        "category": "design",
        "description": "",
        "tags": [
            "installation",
            "ar",
            "hybrid",
            "phygital",
            "co-creation",
            "point cloud notation",
            "tool",
            "volumetric design"
        ],
        "video": "https://pub-6f1f448701a747e7a713d859704dce6c.r2.dev/VideoClouder5.mp4",
        "image": "",
        "embed": "",
        "videoStart": "00:04",
        "detailPage": "https://aut.cc/ausstellungen/potenziale-3",
        "year": "2021–2022",
        "type": "installation, exhibition",
        "institution": "Potentiale 3,  Innsbruck",
        "links": []
    },
    {
        "id": "tune-our-block",
        "title": "Tune Our Block",
        "category": "research",
        "description": "",
        "tags": [
            "urban design",
            "vienna",
            "participation",
            "co-creation",
            "superblock",
            "pedestrianization"
        ],
        "video": "",
        "image": "images\\TuneOurBlock1.jpg",
        "embed": "",
        "videoStart": "",
        "detailPage": "https://www.tuneourblock.eu/",
        "year": "2021-2024",
        "type": "AIT research project",
        "institution": "AIT",
        "links": []
    },
    {
        "id": "sfb",
        "title": "SFB",
        "category": "research",
        "description": "",
        "tags": [
            "research",
            "architecture",
            "digital",
            "ai",
            "point cloud notation"
        ],
        "video": "https://pub-6f1f448701a747e7a713d859704dce6c.r2.dev/FinalMovie05.mp4",
        "image": "",
        "embed": "",
        "videoStart": "00:35",
        "detailPage": "https://acd.tuwien.ac.at/",
        "year": "2020–2024",
        "type": "UIBK research project",
        "institution": "FWF",
        "links": []
    },
    {
        "id": "deep-volumes-house-for-an-artist",
        "title": "Deep Volumes – House for an Artist",
        "category": "teaching",
        "description": "",
        "tags": [
            "volumetric design",
            "point cloud notation"
        ],
        "video": "",
        "image": "images\\houseForAnArtist.gif",
        "embed": "",
        "videoStart": "",
        "detailPage": "",
        "year": "2020-2021",
        "type": "design studio (BA thesis)",
        "institution": "isd – University Innsbruck",
        "links": []
    },
    {
        "id": "complex-collapsible-structures",
        "title": "Complex Collapsible Structures",
        "category": "teaching",
        "description": "",
        "tags": [
            "origami",
            "volumetric design",
            "structure"
        ],
        "video": "https://youtu.be/e4TjZc1n6-Q",
        "image": "",
        "embed": "",
        "videoStart": "",
        "detailPage": "https://www.aag2020.com/complex-collapsible-structures",
        "year": "2020",
        "type": "workshop",
        "institution": "AAG",
        "links": []
    },
    {
        "id": "tpt-edibles",
        "title": "But The Broth was good",
        "category": "vorbrenner scholarship",
        "description": "",
        "tags": [
            "installation",
            "weather",
            "climate",
            "food",
            "spherification",
            "art",
            "performance"
        ],
        "video": "https://vimeo.com/319346806?fl=pl&fe=sh",
        "image": "",
        "embed": "",
        "videoStart": "01:26",
        "detailPage": "https://temporaryedible.wordpress.com/",
        "year": "2018",
        "type": "installation, exhibition, dinner",
        "institution": "Vorbrenner Brux Freies Theater  Innsbruck",
        "links": []
    },
    {
        "id": "society-in-motion",
        "title": "Society in Motion",
        "category": "teaching",
        "description": "",
        "tags": [
            "society in motion",
            "workshop"
        ],
        "video": "videos\\SIM 2019_daily commuting.mp4",
        "image": "",
        "embed": "",
        "videoStart": "00:01",
        "detailPage": "https://www.uni.li/de/projekte/society-motion",
        "year": "2018",
        "type": "Erasmus+ workshop series",
        "institution": "erasmus+ Society in Motion – Bergen, Vienna, Vaduz",
        "links": []
    },
    {
        "id": "the-permanently-temporary",
        "title": "The Permanently Temporary",
        "category": "project",
        "description": "",
        "tags": [
            "storytelling",
            "time",
            "point cloud notation"
        ],
        "video": "https://www.youtube.com/watch?v=gSsksMNuURc",
        "image": "",
        "embed": "",
        "videoStart": "02:15",
        "detailPage": "https://www.youtube.com/@dgke90/videos",
        "year": "2017",
        "type": "DIPLOMA project",
        "institution": "University of Applied Art Vienna | Studio Hani Rashid",
        "links": []
    }
];

const aboutContent = {
    "bio": [
        "I am an architect and researcher working at the intersection of design, technology, and urban systems. My work focuses on how computational tools—from digital twins to emerging forms of agentic AI—can support new ways of understanding, shaping, and maintaining our built environment.",
        "I am particularly interested in how technology can enhance design communication: between people, between disciplines, and increasingly between humans and machines. Rather than simplifying complexity, I see these tools as a way to engage with it—making the layered, dynamic nature of cities more accessible and actionable.",
        "Cities, to me, are spaces of accumulation: of histories, infrastructures, cultures, and relationships. I am interested in how we can sustain this diversity—social, cultural, and physical—while developing new design methods that operate across scales, from buildings to territories.",
        "My current work explores early-stage design processes that integrate environmental, mobility, and spatial intelligence. At the same time, I am drawn to questions of co-creation and co-design: how we can move away from rigid methodologies and instead create frameworks that bring us closer to each other, and to the spaces we inhabit.",
        "I am inspired by thinkers and practitioners such as Shannon Mattern, Dark Matter Labs, David Deutsch, Sarah Walker, Bret Victor and Ursula K. Le Guin (just to mention a few)—voices that engage deeply with systems, knowledge, and alternative ways of thinking about the world.",
        "Lately, I have been thinking about communication — how its forms and rhythms shape collaboration, design processes, and collective understanding. This has drawn me toward a question I find hard to let go of: what happens to spatial thinking when we stop touching and start talking? **As natural language becomes an interface for design, something shifts in how we compose and reason about space** — and I'm still figuring out what that means."
    ],
    "sections": [
        {
            "heading": "Education",
            "items": [
                "PhD Architecture — University of Innsbruck (2020–present)",
                "Magister Architecture (Bachelor + Master) — University of Applied Arts, Vienna (2010–2017)"
            ]
        },
        {
            "heading": "Current Positions",
            "items": [
                "Research Engineer — AIT Austrian Institute of Technology, Center for Energy, Vienna",
                "External Lecturer — University of Innsbruck"
            ]
        },
        {
            "heading": "Selected Experience",
            "items": [
                "Senior Scientist — University of Innsbruck / Integratives Design (2023–2024)",
                "Senior Lecturer — University of Innsbruck (2020–2023)",
                "Architecture Lecturer — University Kassel (2017–2023)",
                "Geometrist — Studio Olafur Eliasson, Berlin (2019–2020)",
                "Software Instructor — Bollinger+Grohmann / Karamba 3D (2018–2019)",
                "Architect — Studio Carl Pruscha, Vienna (2016–2018)"
            ]
        },
        {
            "heading": "Contact",
            "items": [
                "vikisandor.tpt@gmail.com",
                "viktoria.sandor@ait.ac.at"
            ]
        }
    ]
};
